### ISSUE TITLE
Health check performed via CLI causing error in  SPIRE agent log

### ISSUE THREAD

**Issue by elinesterov** [spiffe/spire#1537]
* **Version**: v.0.9.2
* **Platform**: 4.14.81.bm.15-amd64 #1 SMP Debian 4.14.81.bm.15 Sun Sep 8 05:02:31 UTC 2019 x86_64 GNU/Linux
* **Subsystem**:  SPIRE agent health check cli

SPIRE agent is attested to server. If perform periodic health checks via CLI similar to https://github.com/spiffe/spire-tutorials/blob/master/k8s/quickstart/agent-daemonset.yaml 
```
          livenessProbe:
            exec:
              command:
                - /opt/spire/bin/spire-agent
                - healthcheck
                - -socketPath
                - /run/spire/sockets/agent.sock
```
will cause error message in spire-agent log. The same error message is  printed in cli output if `-verbose` flag is used.
```
spire-agent healthcheck -socketPath /opt/spire/agent/sockets/agent.sock -verbose
Contacting Workload API...
Workload API returned rpc error: code = PermissionDenied desc = no identity issued
Agent is healthy.
```

in the spire-agent log it produce similar log record:
```
time="2020-05-07T03:31:13+08:00" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
```

So if anyone is using this mechanism to do a health check will cause spire-agent log filled with error and add bunch of noise if you do it in production. As a workaround you can use http based liveness probe which doesn't cause such issue.

Should we use the common mechanism for both ways to perform health check (CLI and HTTP based)?
