### ISSUE TITLE
OIDC Discovery Provider should support fetching the bundle over the server TCP endpoint

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#2106]
The OIDC Discovery Provider supports obtaining the bundle via two methods.

- The Workload API
- The Server API unix domain socket

It does not support obtaining the bundle via the Server API TCP endpoint, since historically the bundle was not available to unauthenticated workloads with the Node API. However, the (newer) Bundle API supports fetching the bundle without being authenticated.

Supporting fetching the bundle via the Bundle API on the TCP endpoint can simplify deployment since it doesn't require 1) an agent and corresponding workload registration for the OIDC provider process, or 2) access to the Server API Unix domain socket, which grants administrative privileges for all APIs.

This issue is to track adding that support. Namely:

- The server_api section of the configuration should gain a "bootstrap bundle" configurable, since it will need to validate the server's TLS certificate, at least for the initial connection.
- The  config validation code should accept non "unix://" addresses for the server address
- When connecting over TCP, the discovery provider should properly validate the server certificate

**Comment by colek42** [comment]
We did this with a socat sidecar container to expose the registration API.

```
...
        - name: socat
          image: alpine/socat
          args:
            - tcp-listen:8082,fork,reuseaddr
            - unix-connect:/run/spire/sockets/spire-registration.sock
...
```
