### ISSUE TITLE
Support the new SPIFFE Auth validator in Envoy

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#2420]
Envoy has recently gained support for a SPIFFE Auth extension that supports authenticating identities from multiple trust domains with a single validation context.

It fits into the `custom_validator_config` field of the CertificateValidationContext.

This issue tracks the work to add support for this extension to the SDS implementation provided by the agent.

More info on the extension can be found [here](https://www.envoyproxy.io/docs/envoy/v1.18.2/api-v3/extensions/transport_sockets/tls/v3/tls_spiffe_validator_config.proto)

**Comment by MarcosDY** [comment]
In current implementation we allow returning a single Validation context with its bundle, based on the provided name:
```
            validation_context_sds_secret_config:
              name: "spiffe://domain.test"
              sds_config:
                api_config_source:
                  api_type: GRPC
                  grpc_services:
                    envoy_grpc:
                      cluster_name: spire_agent
                  transport_api_version: V3
                resource_api_version: V3
```
In this example we choose to return the bundle with TD `spiffe://domain.test`
Or if [default_bundle_name](https://github.com/spiffe/spire/blob/main/doc/spire_agent.md#sds-configuration) is used, it can be returned (it is done this way to be able to return the agent's bundle, for ISTIO compatibility).
It is even possible to return a federated bundle if it is chosen as a name.
However, with this new feature we must be able to return multiple bundles, that can be used to authenticate the caller's identity.
But when must we return all those new bundles?
Here we have some options:
1- add a new configurable in agent's level that enables this feature.
2- add a constant that a user can choose as `resource name` and when it is provided return a `custom_validation_context` instead of regular validation_context.
3- update default bundle implementation to start returning all.
