### ISSUE TITLE
Envoy JWT Auth Helper

### ISSUE THREAD

**Issue by gadinaor-r7** [spiffe/spire#2774]
Looking at the tutorials - https://spiffe.io/docs/latest/microservices/envoy-jwt/readme/#about-envoy-jwt-auth-helper

There is a reference to Envoy JWT Auth Helper and a reference to this docker image us.gcr.io/scytale-registry/envoy-jwt-auth-helper

```yaml
      - name: auth-helper
        image: us.gcr.io/scytale-registry/envoy-jwt-auth-helper@sha256:e55ce5fd42f13c5475b285a848c5f83bc4a335a93d7f934d3ac884920045fc96
        imagePullPolicy: IfNotPresent
        args:  ["-config", "/run/envoy-jwt-auth-helper/config/envoy-jwt-auth-helper.conf"]
        ports:
        - containerPort: 9011
        volumeMounts:
        - name: envoy-jwt-auth-helper-config
          mountPath: "/run/envoy-jwt-auth-helper/config"
          readOnly: true
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
```

Where is the source code of this image ?
