### ISSUE TITLE
SpiffeID CRD dnsNames no longer populated in SAN

### ISSUE THREAD

**Issue by sjberman** [spiffe/spire#3184]
After updating from 1.3.0 to 1.3.1, I'm seeing that the dnsNames defined in a workload's SpiffeID CRD are no longer being populated in the certificate's `X509v3 Subject Alternative Name`.

SpiffeID CRD:

```
spec:
  dnsNames:
  - my-workload-75f5b67547-mnz29
  - my-workload.my-namespace.svc
  spiffeId: spiffe://example.org/ns/my-namespace/sa/my-workload 
```

SAN when running with 1.3.0:

```
X509v3 Subject Alternative Name:
                DNS:my-workload-75f5b67547-mnz29, DNS:my-workload.my-namespace.svc, URI:spiffe://example.org/ns/my-namespace/sa/my-workload
```

SAN when running with 1.3.1:

```
X509v3 Subject Alternative Name:
                URI:spiffe://example.org/ns/my-namespace/sa/my-workload
```
