### ISSUE TITLE
oidc-discovery-provider healthcheck endpoint does not work

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/spire#3572]
* **Version**: 1.5.0
* **Platform**: EKS 1.23
* **Subsystem**: spire-oidc-provider

Using the scratch images on `ghcr.io` I can't use the following readiness probe anymore.

```yaml
readinessProbe:
  exec:
    command: ["/bin/ps", "aux", "|", "grep", "oidc-discovery-provider -config /run/spire/oidc/config/oidc-discovery-provider.conf"]
```

However the healthcheck endpoint also doesn't work due to the fact it only listens on localhost.

https://github.com/spiffe/spire/blob/main/support/oidc-discovery-provider/main.go#L103

See here my k8s httpGet probes.

```yaml
          readinessProbe:
            httpGet:
              path: /ready
              port: 8008
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /live
              port: 8008
            initialDelaySeconds: 5
            periodSeconds: 5
```

These fail with the following message:

```shell
Readiness probe failed: Get "http://10.0.12.97:8008/ready": dial tcp 10.0.12.97:8008: connect: connection refused
Liveness probe failed: Get "http://10.0.12.97:8008/live": dial tcp 10.0.12.97:8008: connect: connection refused
```

As you can see these probes do not use localhost, but the pod IP.
