### ISSUE TITLE
Sha256sums on source code release artifacts

### ISSUE THREAD

**Issue by edwbuck** [spiffe/spire#4082]
Seems inconsistent to provide sha256sum checksums on built release artifacts, but not on the source zip and tgz files.

This can be accomplished by a post-release github action, similar to

```
# release.yml - Automatic creation of sha256 for release tarball

name: goprox release action
run-name: ${{ github.actor }} is publishing release ${{ github.ref_name }}
on:
  release:
    types: [published]
jobs:
  sha256:
    name: sha256
    runs-on: ubuntu-latest
    steps:
      - name: Tarball url
        run: echo "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"
      - name: Create tarball sha256 
        run: curl -sL "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz" | shasum -a 256 | cut -d " " -f 1
```
