### ISSUE TITLE
Unable to attest k8s workload inside a microVM

### ISSUE THREAD

**Issue by Joffref** [spiffe/spire#4522]
I'm looking to use SPIRE along kata-containers (microVM) on kubernetes. I'm facing an issue, when I mount the unix socket inside my pod the connection to it is refused whereas in a pod with containerd it works. Would you have any thoughts on that?

**Logs**
```
level=error msg="Failed to watch the Workload API: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /spiffe-workload-api/spire-agent.sock: connect: connection refused\""
```
**Further information**
- Used CSI driver: https://github.com/spiffe/spiffe-csi
- Deployment used:
```
apiVersion: v1
kind: Pod
metadata:
  name: example-workload
spec:
  containers:
  - name: example-workload
    image: spiffe-csi-driver-example-workload:example
    imagePullPolicy: Never
    volumeMounts:
    - name: spiffe-workload-api
      mountPath: /spiffe-workload-api
      readOnly: true
    env:
    - name: SPIFFE_ENDPOINT_SOCKET
      value: unix:///spiffe-workload-api/spire-agent.sock
  volumes:
  - name: spiffe-workload-api
    csi:
      driver: "csi.spiffe.io"
      readOnly: true
 ```
