### ISSUE TITLE
[Question] PersistentVolume for `/run/spire/data`

### ISSUE THREAD

**Issue by glazychev-art** [spiffe/spire#4751]
Hello,
We are using spire for our k8s use-cases. The setup is mostly based on [this quickstart example](https://github.com/spiffe/spire-tutorials/tree/main/k8s/quickstart).
We noticed, that spire-server `StatefulSet` requires `PersistentVolume`:
```
 ...
  volumeClaimTemplates:
    - metadata:
        name: spire-data
        namespace: spire
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```
that is mounted to `/run/spire/data`
 
We also see that spire-server works if `volumeClaimTemplates` and `volumeMounts: spire-data` are not specified.
 
Could you please explain why `PersistentVolume` is used for `/run/spire/data`?
Is it correct to work without it? And what is the best approach when using spire in production?

Thanks
