### ISSUE TITLE
Config parsing issue in spire server k8s psat node attestor in json mode with multiple clusters

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spire#4962]
If adding a second cluster to a kubernetes psat node attestor when configured in json mode fails to parse with:
```
plugin "NodeAttestor"/"k8s_psat" declared more than once
2024-03-01T03:25:32Z	INFO	setup	Config loaded	{"cluster name": "production", "cluster domain": "cluster.local", "trust domain": "production.other", "ignore namespaces": ["kube-system", "kube-public", "local-path-storage"], "gc interval": "10s", "spire server socket path": "/tmp/spire-server/private/api.sock", "class name": "spire-server-spire", "handle crs without class name": false, "reconcile ClusterSPIFFEIDs": true, "reconcile ClusterFederatedTrustDomains": true, "reconcile ClusterStaticEntries": true}
2024-03-01T03:25:32Z	INFO	setup	Dialing SPIRE Server socket
2024-03-01T03:25:33Z	ERROR	setup	unable to dial SPIRE Server socket	{"error": "failed to dial API socket: context canceled"}
main.run
	/workspace/cmd/main.go:224
main.main
	/workspace/cmd/main.go:91
runtime.main
	/usr/local/go/src/runtime/proc.go:267
```

<details>
  <summary>Non Working Configuration (multiple clusters)</summary>

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-server
  namespace: default
data:
  server.conf: |
    {
      "health_checks": {
        "bind_address": "0.0.0.0",
        "bind_port": "8080",
        "listener_enabled": true,
        "live_path": "/live",
        "ready_path": "/ready"
      },
      "plugins": {
        "DataStore": [
          {
            "sql": {
              "plugin_data": {
                "connection_string": "/run/spire/data/datastore.sqlite3",
                "database_type": "sqlite3"
              }
            }
          }
        ],
        "KeyManager": [
          {
            "disk": {
              "plugin_data": {
                "keys_path": "/run/spire/data/keys.json"
              }
            }
          }
        ],
        "NodeAttestor": [
          {
            "k8s_psat": {
              "plugin_data": {
                "clusters": {
                  "example-cluster": {
                    "allowed_node_label_keys": [],
                    "allowed_pod_label_keys": [],
                    "audience": [
                      "spire-server"
                    ],
                    "service_account_allow_list": [
                      "default:release-name-agent"
                    ]
                  },
                  "other": {
                    "allowed_node_label_keys": [],
                    "allowed_pod_label_keys": [],
                    "audience": [
                      "spire-server"
                    ],
                    "kube_config_file": "/kubeconfigs/other",
                    "service_account_allow_list": "spire-system:spire-agent-upstream"
                  }
                }
              }
            }
          }
        ],
        "Notifier": [
          {
            "k8sbundle": {
              "plugin_data": {
                "config_map": "spire-bundle",
                "namespace": "default"
              }
            }
          }
        ]
      },
      "server": {
        "audit_log_enabled": false,
        "bind_address": "0.0.0.0",
        "bind_port": "8081",
        "ca_key_type": "rsa-2048",
        "ca_subject": [
          {
            "common_name": "example.org",
            "country": [
              "ARPA"
            ],
            "organization": [
              "Example"
            ]
          }
        ],
        "ca_ttl": "24h",
        "data_dir": "/run/spire/data",
        "default_jwt_svid_ttl": "1h",
        "default_x509_svid_ttl": "4h",
        "jwt_issuer": "https://oidc-discovery.example.org",
        "log_level": "info",
        "trust_domain": "example.org"
      }
    }
```
</details>

<details>
  <summary>Working Configuration (single cluster)</summary>

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-server
  namespace: default
data:
  server.conf: |
    {
      "health_checks": {
        "bind_address": "0.0.0.0",
        "bind_port": "8080",
        "listener_enabled": true,
        "live_path": "/live",
        "ready_path": "/ready"
      },
      "plugins": {
        "DataStore": [
          {
            "sql": {
              "plugin_data": {
                "connection_string": "/run/spire/data/datastore.sqlite3",
                "database_type": "sqlite3"
              }
            }
          }
        ],
        "KeyManager": [
          {
            "disk": {
              "plugin_data": {
                "keys_path": "/run/spire/data/keys.json"
              }
            }
          }
        ],
        "NodeAttestor": [
          {
            "k8s_psat": {
              "plugin_data": {
                "clusters": {
                  "example-cluster": {
                    "allowed_node_label_keys": [],
                    "allowed_pod_label_keys": [],
                    "audience": [
                      "spire-server"
                    ],
                    "service_account_allow_list": [
                      "default:release-name-agent"
                    ]
                  }
                }
              }
            }
          }
        ],
        "Notifier": [
          {
            "k8sbundle": {
              "plugin_data": {
                "config_map": "spire-bundle",
                "namespace": "default"
              }
            }
          }
        ]
      },
      "server": {
        "audit_log_enabled": false,
        "bind_address": "0.0.0.0",
        "bind_port": "8081",
        "ca_key_type": "rsa-2048",
        "ca_subject": [
          {
            "common_name": "example.org",
            "country": [
              "ARPA"
            ],
            "organization": [
              "Example"
            ]
          }
        ],
        "ca_ttl": "24h",
        "data_dir": "/run/spire/data",
        "default_jwt_svid_ttl": "1h",
        "default_x509_svid_ttl": "4h",
        "jwt_issuer": "https://oidc-discovery.example.org",
        "log_level": "info",
        "trust_domain": "example.org"
      }
    }
```
