### ISSUE TITLE
SPIRE Agent Custom Plugin Path Permission Denied

### ISSUE THREAD

**Issue by vicshi06** [spiffe/spire#5039]
Hi,

I built a custom plugin binary, and I tried to use it in the spire agent. However, when I log the agent, it keeps saying `Permission denied` when it tries to grab my custom plugin binary, even though I have double checked to make sure that local directory has the user and group set to 1000:1000. 

As you can see below, I have also added a debug sidecar container into  the pod to verify that path is correctly mounted into the pod and has the correct user and group set. 

Interestingly, even if I use `/run/spire/bundle/bundle.crt` for my custom plugin's `plugin_cmd`, it still says permission denied.

Any thoughts on this? We have been stuck on this for 2 weeks now. Is this an issue with CSI driver?

I am using this to build my binary. `export GOOS=linux; export GOARCH=amd64; go build -o sgx_agent_plugn`

Here is my `agent.conf`

```
agent {
      data_dir = "/run/spire"
      log_level = "DEBUG"
      server_address = "spire-server"
      server_port = "8081"
      socket_path = "/run/secrets/workload-spiffe-uds/socket"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = "cluster1.demo"
      sds = {
        default_svid_name = "default"
        default_bundle_name = "null"
        default_all_bundles_name = "ROOTCA"
      }
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          # NOTE: Change this to your cluster name
          cluster = "cluster1"
        }
      }

      NodeAttestor "sgx_plugin" {
        plugin_cmd = "/run/spire/custom/sgx_agent_plugin"
        plugin_checksum = "e62e6cab750f98ed125c70cfb31bd94ff04607ccdab0bffea029b37085100b60"
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          # Defaults to the secure kubelet port by default.
          # Minikube does not have a cert in the cluster CA bundle that
          # can authenticate the kubelet cert, so skip validation.
          skip_kubelet_verification = true

          # We need to set disable_container_selectors = true if we make holdApplicationUntilProxyStarts = true in istio
          # see https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig
          # If true, container selectors are not produced.
          # This can be used to produce pod selectors when the workload pod is known
          # but the workload container is not ready at the time of attestation.
          # disable_container_selectors = true
        }
      }

      WorkloadAttestor "unix" {
          plugin_data {
          }
      }

    }
```

And here is my yaml for the SPIRE Agent DaemonSet:

```
# SPIRE Agent DaemonSet.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: spire
  labels:
    app: spire-agent
spec:
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: spire-agent
      containers:
        - name: debug-sidecar
          image: alpine:latest
          command: ["tail", "-f", "/dev/null"]
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: sgx-plugin
              mountPath: /run/spire/custom
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-bundle
              mountPath: /run/spire/bundle
              readOnly: true
            - name: spire-agent-socket-dir
              mountPath: /run/secrets/workload-spiffe-uds
            - name: spire-token
              mountPath: /var/run/secrets/tokens
        - name: spire-agent
          image: ghcr.io/spiffe/spire-agent:1.5.4
          imagePullPolicy: IfNotPresent
          args: ["-config", "/run/spire/config/agent.conf"]
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: sgx-plugin
              mountPath: /run/spire/custom
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-bundle
              mountPath: /run/spire/bundle
              readOnly: true
            - name: spire-agent-socket-dir
              mountPath: /run/secrets/workload-spiffe-uds
            - name: spire-token
              mountPath: /var/run/secrets/tokens
        # This is the container which runs the SPIFFE CSI driver.
        - name: spiffe-csi-driver
          image: ghcr.io/spiffe/spiffe-csi-driver:0.2.0
          imagePullPolicy: IfNotPresent
          args: [
              "-workload-api-socket-dir", "/spire-agent-socket",
              "-csi-socket-path", "/spiffe-csi/csi.sock",
          ]
          env:
            # The CSI driver needs a unique node ID. The node name can be
            # used for this purpose.
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: sgx-plugin
              mountPath: /run/spire/custom
            # The volume containing the SPIRE agent socket. The SPIFFE CSI
            # driver will mount this directory into containers.
            - mountPath: /spire-agent-socket
              name: spire-agent-socket-dir
              readOnly: true
            # The volume that will contain the CSI driver socket shared
            # with the kubelet and the driver registrar.
            - mountPath: /spiffe-csi
              name: spiffe-csi-socket-dir
            # The volume containing mount points for containers.
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
          securityContext:
            privileged: true
        # This container runs the CSI Node Driver Registrar which takes care
        # of all the little details required to register a CSI driver with
        # the kubelet.
        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.4.0
          imagePullPolicy: IfNotPresent
          args: [
              "-csi-address", "/spiffe-csi/csi.sock",
              "-kubelet-registration-path", "/var/lib/kubelet/plugins/csi.spiffe.io/csi.sock",
          ]
          volumeMounts:
            - name: sgx-plugin
              mountPath: /run/spire/custom
            # The registrar needs access to the SPIFFE CSI driver socket
            - mountPath: /spiffe-csi
              name: spiffe-csi-socket-dir
            # The registrar needs access to the Kubelet plugin registration
            # directory
            - name: kubelet-plugin-registration-dir
              mountPath: /registration
      volumes:
        - name: sgx-plugin
          persistentVolumeClaim:
            claimName: custom-plugin-vc
        - name: spire-config
          configMap:
            name: spire-agent
        - name: spire-bundle
          configMap:
            name: spire-bundle
        - name: spire-token
          projected:
            sources:
              - serviceAccountToken:
                  path: spire-agent
                  expirationSeconds: 7200
                  audience: spire-server
        # This volume is used to share the workload api socket between the
        # CSI driver and SPIRE agent
        - name: spire-agent-socket-dir
          emptyDir: {}
        # This volume is where the socket for kubelet->driver communication lives
        - name: spiffe-csi-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.spiffe.io
            type: DirectoryOrCreate
        # This volume is where the SPIFFE CSI driver mounts volumes
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        # This volume is where the node-driver-registrar registers the plugin
        # with kubelet
        - name: kubelet-plugin-registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
```
