### ISSUE TITLE
Secret Store CSI Provider for SPIRE

### ISSUE THREAD

**Issue by fengyu225** [spiffe/spire#6007]
# Proposal: Secret Store CSI Provider for SPIRE

## Overview
This proposal introduces a Secret Store CSI Driver Provider for SPIRE to enable efficient delivery of SPIFFE Verifiable Identity Documents (SVIDs) to workloads in Kubernetes clusters, focusing on resource efficiency for large-scale deployments.

## Problem Statement
In large Kubernetes environments (such as 100k+ pods), approaches like SPIFFE-helper sidecars could consume substrantial resources:
- ~5,000 vCPU cores (0.05 vCPU per sidecar)
- ~10,000 GB RAM (0.1 GB per sidecar)
- 2.5k EC2 m5.large instances
- $172k/month in infrastructure costs

These resource requirements create challenges for efficiency and cost, particularly for organizations with workloads at scale.

## Proposed Solution
Implement a Secret Store CSI Driver Provider for SPIRE that operates at the node level rather than pod level. With same workloads scale (100k+ pods) this resulte in:
- 2,000 vCPU cores (1 vCPU per node with 50 pods per node)
- 2,000 GB RAM (1 GB per node)
- 1k EC2 m5.large instances
- $69,120/month

This represents a 60% reduction in resource consumption and associated infrastructure costs.

## Design
The solution leverages the [Secret Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/) - a Kubernetes solution that dynamically injects secrets, certificates, and credentials from external systems into pods as ephemeral volumes and implement a provider for requesting and delivering SPIRE SVID to workloads.

Components:
1. Secret Store CSI Driver deployed as DaemonSet
2. SPIRE Provider which is gRPC server interfacing with CSI Driver
3. SPIRE Agent with configuration that allows the SPIRE Secret Store CSI provider as authorized delegates for Delegated Identity API

Workflow:
- Pod with configured SPIRE provider volume starts
- CSI driver communicates with SPIRE provider via gRPC
- SPIRE provider requests SVID on behalf of pod using namespace and service account as selectors
- SPIRE agent returns SVID to provider
- CSI driver mounts SVIDs as files in pod's specified volume path

![Image](https://github.com/user-attachments/assets/36e05fbe-7e3d-4fc9-a6b2-f20330e8860c)

The following example shows an example [SecretProviderClass](https://secrets-store-csi-driver.sigs.k8s.io/getting-started/usage) for the SPIRE provider:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spire
  namespace: app
spec:
  provider: spire
  parameters:
    useCase: "istio"
    trustDomain: "example.org"
    objects: |
      - objectName: "x509"
        type: "x509-svid"
        filePermission: 0640
        paths:
          - "x509/cert.pem"
          - "x509/key.pem"
          - "x509/bundle.pem"
      - objectName: "app1-jwt"
        type: "jwt-svid"
        filePermission: 0640
        audience:
          - "app1"
        paths:
          - "jwt/app1.token"
```

## Workload Attestation
The SPIRE provider can use Delegated Identity API with two attestation methods:

1. **Selector-based attestation**: Provider builds selectors (namespace, service account, pod UID) and sends to SPIRE agent
2. **PID-based attestation**: Provider identifies container PID and provides it to SPIRE agent, which performs attestation

For PID-based attestation, the provider:
- Queries kubelet API for container ID using pod UID
- Inspects cgroup under host PID namespace to identify container process PID
- Provides PID to SPIRE agent via `SubscribeToX509SVIDsRequest`

## Requirements
- hostNetwork enabled on SPIRE CSI provider pod (for kubelet API access)
- hostPID enabled on SPIRE CSI provider pod (for PID-based attestation)
- SPIRE CSI provider authorized as delegate in SPIRE agent configuration

## Proof of concept
- [Proof of concept implementation](https://github.com/spiffe/spire-secret-store-csi-provider-poc)
