### ISSUE TITLE
BundlePublisher k8s_configmap create via server side apply

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spire#6136]
Normally, `create` actions via k8s can not be restricted to a particular `resourceName`, allowing any configmap to be created by the actor.

Apparently, a policy like:
```
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["test"]
  verbs: ["patch","create","get"]
```
can be made to work, provided the creation of the configmap is done via the server side apply mechanism. Restricting the ability to create arbitrary configmaps would enhance security of the final deployment.
